### ISSUE TITLE
Video streaming app pod going to CrashLoopBackOff

### ISSUE THREAD

**Issue by didier-durand** [deislabs/akri#100]
Hello,

**Describe the bug**

When replicating the end-to-demo with MicroK8s (Ubuntu instance on GC) on my own, the pod of video streaming app goes to CrashLoopBackOff.

All other prior install steps were successful.

I added below the logs of failing pod

Didier

**Output of `kubectl get pods,akrii,akric -o wide`**

microk8s kubectl get all --all-namespaces -o wide
NAMESPACE     NAME                                              READY   STATUS             RESTARTS   AGE   IP            NODE            NOMINATED NODE   READINESS GATES
kube-system   pod/calico-kube-controllers-847c8c99d-65bbl       1/1     Running            0          18m   10.1.54.67    microk8s-akri   <none>           <none>
kube-system   pod/calico-node-xsvqv                             1/1     Running            1          18m   10.128.0.35   microk8s-akri   <none>           <none>
kube-system   pod/coredns-86f78bb79c-dbgm9                      1/1     Running            0          17m   10.1.54.66    microk8s-akri   <none>           <none>
default       pod/akri-agent-daemonset-c88pb                    1/1     Running            0          12m   10.128.0.35   microk8s-akri   <none>           <none>
default       pod/akri-controller-deployment-5b4bb5cbb5-8mlwp   1/1     Running            0          12m   10.1.54.68    microk8s-akri   <none>           <none>
default       pod/akri-video-streaming-app-fd5f4cb7d-fzpcq      0/1     CrashLoopBackOff   7          12m   10.1.54.69    microk8s-akri   <none>           <none>

NAMESPACE     NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE   SELECTOR
default       service/kubernetes                 ClusterIP   10.152.183.1     <none>        443/TCP                  18m   <none>
kube-system   service/kube-dns                   ClusterIP   10.152.183.10    <none>        53/UDP,53/TCP,9153/TCP   17m   k8s-app=kube-dns
default       service/akri-video-streaming-app   NodePort    10.152.183.216   <none>        80:31671/TCP             12m   app=akri-video-streaming-app

NAMESPACE     NAME                                  DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE   CONTAINERS    IMAGES                                   SELECTOR
kube-system   daemonset.apps/calico-node            1         1         1       1            1           kubernetes.io/os=linux   18m   calico-node   calico/node:v3.13.2                      k8s-app=calico-node
default       daemonset.apps/akri-agent-daemonset   1         1         1       1            1           kubernetes.io/os=linux   12m   akri-agent    ghcr.io/deislabs/akri/agent:latest-dev   name=akri-agent

NAMESPACE     NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS                 IMAGES                                                 SELECTOR
kube-system   deployment.apps/coredns                      1/1     1            1           17m   coredns                    coredns/coredns:1.6.6                                  k8s-app=kube-dns
kube-system   deployment.apps/calico-kube-controllers      1/1     1            1           18m   calico-kube-controllers    calico/kube-controllers:v3.13.2                        k8s-app=calico-kube-controllers
default       deployment.apps/akri-controller-deployment   1/1     1            1           12m   akri-controller            ghcr.io/deislabs/akri/controller:latest-dev            app=akri-controller
default       deployment.apps/akri-video-streaming-app     0/1     1            0           12m   akri-video-streaming-app   ghcr.io/deislabs/akri/video-streaming-app:latest-dev   app=akri-video-streaming-app

NAMESPACE     NAME                                                    DESIRED   CURRENT   READY   AGE   CONTAINERS                 IMAGES                                                 SELECTOR
kube-system   replicaset.apps/calico-kube-controllers-847c8c99d       1         1         1       18m   calico-kube-controllers    calico/kube-controllers:v3.13.2                        k8s-app=calico-kube-controllers,pod-template-hash=847c8c99d
kube-system   replicaset.apps/coredns-86f78bb79c                      1         1         1       17m   coredns                    coredns/coredns:1.6.6                                  k8s-app=kube-dns,pod-template-hash=86f78bb79c
default       replicaset.apps/akri-controller-deployment-5b4bb5cbb5   1         1         1       12m   akri-controller            ghcr.io/deislabs/akri/controller:latest-dev            app=akri-controller,pod-template-hash=5b4bb5cbb5
default       replicaset.apps/akri-video-streaming-app-fd5f4cb7d      1         1         0       12m   akri-video-streaming-app   ghcr.io/deislabs/akri/video-streaming-app:latest-dev   app=akri-video-streaming-app,pod-template-hash=fd5f4cb7d

**Kubernetes Version: [e.g. Native Kubernetes 1.19, MicroK8s 1.19, Minikube 1.19, K3s]**

snap list
Name              Version    Rev    Tracking         Publisher          Notes
core              16-2.47.1  10185  latest/stable    canonical✓         core
core18            20200929   1932   latest/stable    canonical✓         base
google-cloud-sdk  316.0.0    157    latest/stable/…  google-cloud-sdk✓  classic
helm              3.4.0      302    latest/stable    snapcrafters       classic
lxd               4.0.3      16922  4.0/stable/…     canonical✓         -
microk8s          v1.19.2    1769   1.19/stable      canonical✓         classic
snapd             2.47.1     9721   latest/stable    canonical✓         snapd

**To Reproduce**
I can publish my script in a repo with corresponding Github workflow to allow you to see full exec log (andreproduce by forking if needed)

**Expected behavior**

Get streaming app pod to Running status

**Logs (please share snips of applicable logs)**

microk8s kubectl logs akri-video-streaming-app-fd5f4cb7d-fzpcq  
Traceback (most recent call last):
  File "./streaming.py", line 33, in <module>
    grpc_port = os.environ[env_var_prefix + 'PORT_GRPC'] # instance services are using the same port by default
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'AKRI_UDEV_VIDEO_SVC_SERVICE_PORT_GRPC'

**Additional context**

GCE instance with Ubuntu LTS 20.04

**Comment by jiria** [comment]
Hello @didier-durand ,

The streaming app will crash with the default configuration if the configuration level service has not been created, which happens if no instances have been found. Can you please share how you deployed Akri, especially the configuration? Also, your output does not correspond to this command:
```
kubectl get pods,akrii,akric -o wide
```
Can you please share output of this command?

**Comment by didier-durand** [comment]
hi,
I did a full reinstall of my Ubuntu and can't get  gst-launch-1.0  commands to work again (video device not properly seen).
Please, have some patience until I understand the root cause and fix.
Sorry for the delay!
didier

**Comment by didier-durand** [comment]
1. I opened a ticket with the v4l2 team: I can't get GStreamer to work with the v4l2sink on Ubuntu 20.04 LTS
2. But, ffmpeg works fine with v4l2sink to generate similar videostreams
3. With those ffmpeg streams, the problem is the same : pod failing in CrashLoopBackoff
4. Below the outcome of the commands that you asked for. NB: no akrii or akric resources available
5. I also added the commannds and logs of the Akri helm chart install and of the install of the streaming application

### get infos on pod, akrii, akric

microk8s kubectl get pods,akrii,akric
NAME                                              READY   STATUS             RESTARTS   AGE
pod/akri-agent-daemonset-2tslp                    1/1     Running            0          87m
pod/akri-controller-deployment-5b4bb5cbb5-b2tjk   1/1     Running            0          87m
pod/akri-video-streaming-app-fd5f4cb7d-9pzbj      0/1     CrashLoopBackOff   21         87m

### Log of Akri helm chart install

helm --kubeconfig "$KUBE_CONFIG" repo add akri-helm-charts https://deislabs.github.io/akri/
  export AKRI_HELM_CRICTL_CONFIGURATION="--set agent.host.crictl=/usr/local/bin/crictl --set agent.host.dockerShimSock=/var/snap/microk8s/common/run/containerd.sock"
  helm install akri akri-helm-charts/akri-dev \
      $AKRI_HELM_CRICTL_CONFIGURATION \
      --set useLatestContainers=true \
      --set udevVideo.enabled=true \
      --set udevVideo.udevRules[0]='KERNEL==\"video[0-9]*\"' \
      --kubeconfig "$KUBE_CONFIG"
  sudo microk8s kubectl wait --for=condition=available --timeout=50s deployment.apps/akri-controller-deployment -n default

WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: kube-config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: kube-config
"akri-helm-charts" has been added to your repositories
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: kube-config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: kube-config
W1106 07:05:29.071185   35919 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W1106 07:05:29.075364   35919 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W1106 07:05:29.233020   35919 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W1106 07:05:29.243928   35919 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
NAME: akri
LAST DEPLOYED: Fri Nov  6 07:05:28 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the Akri Controller:
  kubectl get -o wide pods | grep controller
2. Get the Akri Agent(s):
  kubectl get -o wide pods | grep agent
3. Get the Akri Configuration(s):
  kubectl get -o wide akric
deployment.apps/akri-controller-deployment condition met

### Log of install for video streaming app

sudo microk8s kubectl apply -f "https://raw.githubusercontent.com/deislabs/akri/main/deployment/samples/akri-video-streaming-app.yaml"
  sudo microk8s kubectl wait --for=condition=available --timeout=50s deployment.apps/akri-video-streaming-app -n default
deployment.apps/akri-video-streaming-app created
service/akri-video-streaming-app created
deployment.apps/akri-video-streaming-app condition met

**Comment by didier-durand** [comment]
Due to the recent changes re helm command on [end-to-end-demo.md](https://github.com/deislabs/akri/blob/main/docs/end-to-end-demo.md) , this ticket is no longer valid: I get different results by applying those changes when I try to reproduce the demo. I'll re-open a new issue if needed.
So, closing for now.
