### ISSUE TITLE
[Extensibility] Nessie gRPC

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#103]
**Is your feature request related to a problem? Please describe.**

IIUC Nessie's use of gRPC is redundant.

Having begun implementing a protocol (#85), I used Nessie as a template and realized this.

My lack of familiarity with the gRPC crate used and struggling to understand the architecture of Akri, exacerbated my challenge.

**Is your feature request related to a way you would like Akri extended? Please describe.**

Remove the gRPC code from Nessie to simplify it.

**Describe the solution you'd like**

See above.

**Describe alternatives you've considered**

It's probable that I'm incorrect.

**Additional context**

**Comment by DazWilkin** [comment]
I suspect that gRPC is proposed as a mechanism by which broker clients (!) could connect through a broker's service using a well-defined contract?

**Comment by bfjelds** [comment]
That is correct @DazWilkin ... the gRPC is simply an example of how one might communicate the Nessie broker results to any other pods.  In this case, (unlike the e2e udev camera sample) we did not create the broker client app.
