### ISSUE TITLE
rbac.yaml uses deprecated rbac.authorization.k8s.io/v1beta1 ClusterRole

### ISSUE THREAD

**Issue by bfjelds** [deislabs/akri#119]
**Describe the bug**
RBAC yaml should use non-deprecated rbac.authorization.k8s.io/v1 ClusterRole

**Comment by jiria** [comment]
Once this is fixed, we should try to pick the latest helm again.

**Comment by bfjelds** [comment]
> Once this is fixed, we should try to pick the latest helm again.

At the very least, we should make some kind of plan for when we update our Helm version.  Is it every patch release?  Every minor release?  At face value, I'm not sure what it means to support 3.4.0 but not 3.4.1.

**Comment by bfjelds** [comment]
This was fixed in https://github.com/deislabs/akri/pull/171
