### ISSUE TITLE
Cannot join Akri's Slack workspace via badge on README.md

### ISSUE THREAD

**Issue by didier-durand** [deislabs/akri#129]
**Describe the bug**

(sorry if I am a bit off topic here but I couldn't ask elsewhere like Slack due to my problem)

I cannot join the project's Slack using the badge on README.md

It will redirect me to the page below at https://kubernetes.slack.com/?redir=%2Fmessages%2Fakri

If I do my usual "Continue with Google" (that I use successfully with other Slacks), it will fail. Is it invite-only or something like that?

Thanks 

Didier

<img width="704" alt="image" src="https://user-images.githubusercontent.com/2927957/99279177-3a80e880-2830-11eb-94e8-c48897869685.png">

**Comment by kate-goldenring** [comment]
Hi @didier-durand, it should lead you to sign into Kubernetes slack and then you have to search for the #akri channel. I am not sure if there is a way we can direct you directly to our channel.

**Comment by didier-durand** [comment]
@kate-goldenring : Ok, got it. Maybe, you should mention that people not yet registered to K8s Slack should first go to https://slack.k8s.io/ (I had to Google it) to get the invite for the global Slack and then get to the Akri channel. A couple of sentence in the Contributing section of the README may help.

Anyway, I am in now. Thanks for your help! (closing)

Didier

**Comment by kate-goldenring** [comment]
Great idea! Can do!

**Comment by didier-durand** [comment]
:+1:
