### ISSUE TITLE
'unknown flag: --set agent.host.crictl' on Akri's helm chart install

### ISSUE THREAD

**Issue by didier-durand** [deislabs/akri#142]
**Describe the bug**

I am following the install procedure of end-to-end demo: when executing step 1 of [this section](https://github.com/deislabs/akri/blob/main/docs/end-to-end-demo.md#set-up-akri), I get 

`Error: unknown flag: --set agent.host.crictl`

I have set variable AKRI_HELM_CRICTL_CONFIGURATION properly (I hope...) via
`AKRI_HELM_CRICTL_CONFIGURATION='--set agent.host.crictl=/usr/local/bin/crictl --set agent.host.dockerShimSock=/var/snap/microk8s/common/run/containerd.sock'`

The akri helm repo was properly added via `microk8s helm3 repo add 'akri-helm-charts' 'https://deislabs.github.io/akri/' `on which I get `"akri-helm-charts" has been added to your repositories`

So, what do I do wrong?

Thanks for your help

Didier

**Output of `kubectl get pods,akrii,akric -o wide`**

I did not reach this stage yet

**Kubernetes Version: [e.g. Native Kubernetes 1.19, MicroK8s 1.19, Minikube 1.19, K3s]**

```
microk8s (1.19/edge) v1.19.4 from Canonical* installed
microk8s          v1.19.4    1810   1.19/edge        canonical*         classic

```

1810 is the version of installed snap

**To Reproduce**

run our script at https://github.com/didier-durand/microk8s-akri/blob/main/sh/microk8s-akri.sh  or fork repo and run workflow https://github.com/didier-durand/microk8s-akri/blob/main/.github/workflows/microk8s-akri.yml

**Expected behavior**
Proper installation of Helm chart to be able to continue further in the demo install

**Logs (please share snips of applicable logs)**
 
```
### install akri chart: 
2020-11-20T06:52:02.4560237Z Error: no repositories to show
2020-11-20T06:52:02.8022500Z "akri-helm-charts" has been added to your repositories
2020-11-20T06:52:02.8085732Z critctl path: /usr/local/bin/crictl
2020-11-20T06:52:02.9648848Z Error: unknown flag: --set agent.host.crictl
```
Full log (Github interactive interface): https://github.com/didier-durand/microk8s-akri/actions/runs/373835396

Full log (text form) available at https://pipelines.actions.githubusercontent.com/YT1CGW2Wkplohu80t7gWKaYhzh929U5dpGIo69C98k0YO1N9dm/_apis/pipelines/1/runs/25/signedlogcontent/3?urlExpires=2020-11-20T06%3A53%3A29.4204408Z&urlSigningMethod=HMACV1&urlSignature=Z2xBZfORSHyClYKfz86VocTNemnkMl4zLflU%2B3S2Dqg%3D

**Additional context**

**Comment by bfjelds** [comment]
I'm not a linux scripting expert, but I think this might happen because you are quoting AKRI_HELM_CRICTL_CONFIGURATION (i.e. `"$AKRI_HELM_CRICTL_CONFIGURATION"`) in your helm invocation.  Can you try this instead:

```
    microk8s helm3 install 'akri' 'akri-helm-charts/akri-dev' \
        $AKRI_HELM_CRICTL_CONFIGURATION \
        --set useLatestContainers=true \
        --set udevVideo.enabled=true \
        --set udev.name=akri-udev-video \
        --set udevVideo.udevRules[0]='KERNEL=="video[0-9]*"' \
        --set udev.brokerPod.image.repository="ghcr.io/deislabs/akri/udev-video-broker:latest-dev"
```

**Comment by didier-durand** [comment]
@bfjelds : you're fully right. I just unduly overprotected my variable with too many quote levels on this one. My bad!
Sorry for the noise.
Closing
Didier

**Comment by kate-goldenring** [comment]
I think it also be because in your script you are missing a couple new line escapes [here](https://github.com/didier-durand/microk8s-akri/blob/dc6c144497df16750c94f27222d3004ebc74076f/sh/microk8s-akri.sh#L307). 
Your install command:
```sh
microk8s helm3 install 'akri' 'akri-helm-charts/akri-dev' \
        --set agent.host.crictl='/usr/local/bin/crictl'
        --set agent.host.dockerShimSock='/var/snap/microk8s/common/run/containerd.sock'
        --set useLatestContainers=true \
        --set udevVideo.enabled=true \
        --set udev.name=akri-udev-video \
        --set udevVideo.udevRules[0]='KERNEL=="video[0-9]*"' \
        --set udev.brokerPod.image.repository="ghcr.io/deislabs/akri/udev-video-broker:latest-dev"
```
Install command with missing escapes:
```sh
microk8s helm3 install 'akri' 'akri-helm-charts/akri-dev' \
        --set agent.host.crictl='/usr/local/bin/crictl' \
        --set agent.host.dockerShimSock='/var/snap/microk8s/common/run/containerd.sock' \
        --set useLatestContainers=true \
        --set udevVideo.enabled=true \
        --set udev.name=akri-udev-video \
        --set udevVideo.udevRules[0]='KERNEL=="video[0-9]*"' \
        --set udev.brokerPod.image.repository="ghcr.io/deislabs/akri/udev-video-broker:latest-dev"
```

**Comment by didier-durand** [comment]
@kate-goldenring : Kate, thanks a lot for your thorough review of my intermediate new version removing totally the  $AKRI_HELM_CRICTL_CONFIGURATION that I was overprotecting as per @bfjelds remark above. I'll confirm back here when I reach the fully working demo. Didier

Didier
