### ISSUE TITLE
a small issue

### ISSUE THREAD

**Issue by zzhzzhzz** [deislabs/akri#151]
When I used the helm to install the Akri,I got an Error-- no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1".  And then I found the CRD is the use of apiextensions. K8s. IO/v1beta1 apiversion.  But after I fixed it, the following mistakes popped up.（May be my knowledge point is relatively weak）
Error: failed to install CRD crds/akri-configuration-crd.yaml: CustomResourceDefinition.apiextensions.k8s.io "configurations.akri.sh" is invalid: [spec.versions[0].additionalPrinterColumns[0].JSONPath: Required value, spec.versions[0].additionalPrinterColumns[1].JSONPath: Required value, spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v0", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc005e8c630), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition{apiextensions.CustomResourceColumnDefinition{Name:"Capacity", Type:"string", Format:"", Description:"The capacity for each Instance discovered", Priority:0, JSONPath:""}, apiextensions.CustomResourceColumnDefinition{Name:"Age", Type:"date", Format:"", Description:"", Priority:0, JSONPath:""}}}}: per-version schemas may not all be set to identical values (top-level validation should be used instead), spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v0", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc005e8c630), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition{apiextensions.CustomResourceColumnDefinition{Name:"Capacity", Type:"string", Format:"", Description:"The capacity for each Instance discovered", Priority:0, JSONPath:""}, apiextensions.CustomResourceColumnDefinition{Name:"Age", Type:"date", Format:"", Description:"", Priority:0, JSONPath:""}}}}: per-version additionalPrinterColumns may not all be set to identical values (top-level additionalPrinterColumns should be used instead)]

**Comment by kate-goldenring** [comment]
Hi @zzhzzhzz, what version and distro of Kubernetes are you using? If you are using plain vanilla Kubernetes, Akri only supports versions 1.16  and up. I suspect you might be using version 1.15 and running into the same issue as [this one](https://github.com/knative/eventing/issues/3559).

**Comment by zzhzzhzz** [comment]
Well，I got it！Thank you.
