### ISSUE TITLE
Add `std::cmp::PartialEq` trait to `DiscoveryResult` to facilitate unit testing

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#175]
**Is your feature request related to a problem? Please describe.**

`DiscoveryResult` does not permit equality comparisons which would be useful in e.g. unit testing.

The struct is defined:

```rust
#[derive(Debug, Clone)]
pub struct DiscoveryResult {
    pub digest: String,
    pub properties: HashMap<String, String>,
}
```

**Is your feature request related to a way you would like Akri extended? Please describe.**

Adding `PartialEq` permits e.g. `assert_eq!(_: DiscoveryResult, _: DiscoveryResult)` and this facilitates unit testing.

**Describe the solution you'd like**

```rust
#[derive(Debug, Clone, PartialEq)]
pub struct DiscoveryResult {
    pub digest: String,
    pub properties: HashMap<String, String>,
}
```

**Comment by kate-goldenring** [comment]
Hi @DazWilkin, sounds like a good addition. Would you be interested in adding this to the Agent?
