### ISSUE TITLE
Upgrade to hyper >=0.12.34

### ISSUE THREAD

**Issue by romoh** [deislabs/akri#208]
**Describe the bug**
The version of hyper crate Akri uses introduces a security vulnerability. This is detected using [cargo-audit](https://github.com/RustSec/cargo-audit.) (a tool which inspects Cargo.lock files and compares them against the RustSec Advisory Database, a community database of security vulnerabilities).
I also suggest adding a github workflow to automatically running cargo-audit with pull requests to catch similar issues for newly added code.

**To Reproduce**
1. Install cargo-audit
2. Run cargo-audit -audit
3. Output:
```
Crate:         hyper
Version:       0.11.27
Title:         Flaw in hyper allows request smuggling by sending a body in GET requests
Date:          2020-03-19
ID:            RUSTSEC-2020-0008
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0008
Solution:      Upgrade to >=0.12.34
Dependency tree: 
hyper 0.11.27

```

**Expected behavior**
Akri is expected to use crates that are secure. Any used crates with security vulnerabilities should be updated to latest or substituted.

**Logs (please share snips of applicable logs)**
Above

**Additional context**

**Comment by jiria** [comment]
Can you create a separate issue for automating running of cargo-audit?
