### ISSUE TITLE
ONVIF Camera discovery issue

### ISSUE THREAD

**Issue by Xzatrox** [deislabs/akri#249]
**Describe the bug**
Unable to discover the ONVIF cameras following the provided installation instructions in the repository.

**Output of `kubectl get pods,akrii,akric -o wide`**
pi@raspberrypi:~ $ kubectl get pods,akrii,akric -o wide
NAME                                              READY   STATUS             RESTARTS   AGE   IP               NODE          NOMINATED NODE   READINESS GATES
pod/akri-controller-deployment-56748f985f-dmmz2   1/1     Running            0          45m   10.42.0.11       raspberrypi   <none>           <none>
pod/akri-video-streaming-app-fc8d97f69-k5q65      1/1     Running            0          31m   10.42.0.12       raspberrypi   <none>           <none>
pod/akri-agent-daemonset-fz7rl                    0/1     CrashLoopBackOff   10         29m   192.168.10.100   raspberrypi   <none>           <none>

NAME                               CAPACITY   AGE
configuration.akri.sh/akri-onvif   2          111m

**Kubernetes Version: [e.g. Native Kubernetes 1.19, MicroK8s 1.19, Minikube 1.19, K3s]**
K3s 1.18.9+k3s1

**To Reproduce**
1. Create cluster using k3s
2. Install Akri with the Helm command
3. Try to discover 2 ONVIF cameras connected to the same local network 
4. Discovery done, but connection failed (log attached)

**Expected behavior**
Cameras connection successful and video streaming works fine

**applicable logs attached**
[akri.log](https://github.com/deislabs/akri/files/6004969/akri.log)

**Comment by kate-goldenring** [comment]
Hi @Xzatrox, thanks for finding this bug and adding the logs. It seems like the ONVIF discovery handler should be filtering out or handling IPv6 addresses -- @bfjelds  on thoughts? The failure to do so seems to resolve in the agent panicking [when trying to connect to the endpoint](https://sourcegraph.com/github.com/deislabs/akri/-/blob/shared/src/onvif/mod.rs#L142).

**Comment by bugsboym** [comment]
@kate-goldenring Hello Kate.
We turned off IPv6 camera and now discovery handler finds our camera but now we received messages about "Permission denied". Please see the logs. Thank you!
[akri_new.log](https://github.com/deislabs/akri/files/6021530/akri_new.log)

Also new pod "raspberrypi-akri-onvif-34e973-pod" is trying to start and fails. See the screenshot.
![image](https://user-images.githubusercontent.com/39308676/108693549-a0070400-7506-11eb-9a56-88632b0186ec.png)

**Comment by kate-goldenring** [comment]
Hi @Xzatrox, thanks for confirming that we cant support the IPv6 camera -- we should fix this. The PermissionDenied error in the logs is unrelated to ONVIF discovery. Our Agent uses crictl to query the container runtime to ensure that the Pods that are using Akri resources still exist. When installing Akri, if you are not using vanilla Kubernetes, you have to configure the crictl path. The instructions for installing crictl for K3s and configuring it when installing Akri can be found [in our user guide](https://github.com/deislabs/akri/blob/main/docs/user-guide.md#deploying-akri). We should be reiterating it throughout the rest of our docs, though. 

As for the failing broker pod, does your camera require authentication? Can you see it via the [Onvif Device Manager](https://sourceforge.net/projects/onvifdm/). Our ONVIF sample broker assumes the camera does not require authentication of any sorts.
