### ISSUE TITLE
Consider rename of Configuration.shared

### ISSUE THREAD

**Issue by bfjelds** [deislabs/akri#265]
The general idea of `shared` is can be thought of in a couple ways:
1. a device is shared if several nodes can access it (i.e. ip camera)
2. a device is not shared if it is physically attached to a single node (i.e. a usb camera)

A `shared` device will have a single Instance and a `capacity` that is shared by all the nodes that can access the device.

Is `shared=true|false` the best way to express this?

# Possible ideas
### shared=boolean
Are the devices actually shared?  Does that name make sense?  Is boolean too limiting ... could there be a state that is not described by this?

### local=boolean
Is local too specific?  Can a shared device be considered local?  Can a local device be shared?

### deviceConnectivity=enum
The enum could be any number of ideas:
* SingleNode|MultiNode
* Direct|Indirect
* Synchronous|Asyncronous
* Usb|Bus|Ip

**Comment by kate-goldenring** [comment]
closing and using `shared` until otherwise requested
