### ISSUE TITLE
Provide a list of IP cameras tested with Akri

### ISSUE THREAD

**Issue by igorrudyk** [deislabs/akri#299]
Hello guys,

Could you please provide a list of IP cameras tested with Akri. It would be very helpful.

Thanks
Igor

**Comment by kate-goldenring** [comment]
Hi @igorrudyk we should support all [ONVIF compliant cameras](https://www.onvif.org/conformant-products/). For example, I use [onvif_srvd](https://github.com/KoynovStas/onvif_srvd) to mock an ONVIF camera locally on Linux and pass a fake RTSP stream through it with gstreamer.

Specifically, we have tested and done Akri demos with a RTT-2350 camera, this [Evtevision one](https://www.amazon.com/gp/product/B07XQ66VYG/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1), and this [JideTech one](https://www.amazon.com/gp/product/B081YTV9TY/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1).

**Comment by igorrudyk** [comment]
Hi @kate-goldenring ,
Thank you
