### ISSUE TITLE
Implementing On-Device Audio

### ISSUE THREAD

**Issue by cwoolum** [deislabs/akri#33]
I am currently running a k3s cluster on some Raspberry Pi 4s. Would it be possible for Akri to utilize an audio card on one of these Pi's as an Akri Plugin?

I would assume a device plugin would need to be created. Does this make sense as an Akri use-case?

**Comment by jiria** [comment]
Hello Chris,

If the card gets exposed through udev, you can certainly expose it to pods using Akri, no code change needed. This use case should be covered by Akri as is.

Let us know!

**Comment by kate-goldenring** [comment]
Hi @cwoolum! As @jiria mentioned, our udev protocol supports discovering anything on the Linux device file system. You simply have to specify a [udev rule](https://wiki.archlinux.org/index.php/Udev) that can be used to locate the device[s] in your Configuration. As to making your Akri Configuration, you can either modify our [sample udevVideo Configuration](https://github.com/deislabs/akri/blob/main/docs/udev-sample.md#modifying-the-udev-rule) or [create your own](https://github.com/deislabs/akri/blob/main/docs/modifying-akri-installation.md#generating-modifying-and-applying-a-configuration-yaml). I'll walk you through both. 

We will create a Configuration that will discover all devices in the sound subsytem and deploy an nginx broker pod. Your udev rule will probably be more specific. This rule will discover all devices listed when you run `udevadm trigger --verbose --dry-run --type=devices --subsystem-match=sound`
1. Option 1: Modifying the udevVideo Configuration
Simply run the following on your cluster. Be sure to initialize your cluster for Akri. Steps for this can be found at the beginning of the [rpi4 demo](https://github.com/deislabs/akri/blob/main/docs/rpi4-demo.md).
```
helm repo add akri-helm-charts https://deislabs.github.io/akri/
helm install akri akri-helm-charts/akri \
    --set useLatestContainers=true \
    --set udevVideo.enabled=true \
    --set udevVideo.udevRules[0]='SUBSYSTEM=="sound"' \
    --set udevVideo.brokerPod.image.repository='nginx'
```
You will see nginx brokers deployed to every discovered sound device.

2. Option 2: Create a Configuration
It's easier to work off an existing Configuration, so download the udevVideo one by running:
```
helm template akri akri-helm-charts/akri \
    --set useLatestContainers=true \
    --set udevVideo.enabled=true \
    --set controller.enabled=false \
    --set agent.enabled=false > udevAudio.yaml
```
Open the yaml and remove all RBAC content (everything above line 79).
Feel free to change Configuration name:
```
metadata:
  name: my-udev-audio
```
Change the udev rule to fit your needs:
```
    udev:
      udevRules:
      - SUBSYSTEM=="sound"
```
Change `brokerPodSpec`. Make the broker pod container to point to your broker -- nginx in this example. Delete all teh environment variables, which we specific to cameras. 
```
  brokerPodSpec:
    containers:
    - name: my-broker
      image: "nginx:latest"
      imagePullPolicy: Always
      securityContext:
        privileged: true
      resources:
        limits:
          "{{PLACEHOLDER}}" : "1"
```
Now, install Akri (the controller, agent, and CRDs):
```
helm repo add akri-helm-charts https://deislabs.github.io/akri/
helm install akri akri-helm-charts/akri \
    --set useLatestContainers=true
```
Finally, apply your new udevAudio Configuration with `kubectl apply -f udevAudio.yaml`
You will see nginx brokers deployed to every discovered sound device.

Let me know if you have any questions or run into any problems.

**Comment by kate-goldenring** [comment]
@cwoolum, we have updated our provided Configuration helm templates to be more generic rather than specific to one scenario, usb cameras for udev. Thank you for pointing out this needed change! We have provided [documentation](https://github.com/deislabs/akri/blob/main/docs/udev-configuration.md) on how to customize that generic udev configuration, say to discover on-device audio. I am closing this, but feel free to re-open it if you have any other questions or feel like the documentation could be expanded upon.

**Comment by cwoolum** [comment]
Thanks for the detailed response and the update to the docs! I can't wait to jump into this when I get a chance!
