### ISSUE TITLE
Make device plugin and kubelet path configurable

### ISSUE THREAD

**Issue by rodz** [deislabs/akri#357]
**Is your feature request related to a way you would like Akri extended? Please describe.**
The value for DEVICE_PLUGIN_PATH and KUBELET_SOCKET are not configurable and require hard coded solutions to be changed. By making these values configurable Akri could reach new use unconventional use cases, like the support for running with a Krustlet node.

**Describe the solution you'd like**
At device_plugin_builder.rs the Akri Agent can pull this data from an environment variable instead of the constraints file. Maybe we also need to add a default value in cases where the user doesn’t specify it.

**Describe alternatives you've considered**
This can also be changed using arguments or hard code changes, but the environment variable seams more conventional. 

**Additional context**
There have been some problems while making the Akri Agent connect with Krustlet's device plugin and could only be solved after I had changed this directory to the correct one directly changing the constants.rs file from the Akri Agent.

**Comment by bfjelds** [comment]
maybe we should make K8S_DEVICE_PLUGIN_VERSION configurable too?

**Comment by bfjelds** [comment]
could this be a helm option (like kubeletDevicePlugins)?

**Comment by kate-goldenring** [comment]
> could this be a helm option (like kubeletDevicePlugins)?

I agree. I see this as being analogous to how we allow configuring `DISCOVERY_HANDLERS_DIRECTORY` via the Helm value `.Values.agent.host.discoveryHandlers`

**Comment by rodz** [comment]
Just an update, 
after some investigations I noticed that the device plugin path is already configurable using help with the configuration `.Values.agent.host.kubeletDevicePlugins` so this is a problem only if running the Agent locally (Not using kubernetes).

**Comment by kate-goldenring** [comment]
> agent.host.kubeletDevicePlugin

Good point. It may not be worth adding the plumbing to configure it for when running locally
