### ISSUE TITLE
Question regarding WebUI for Akri 

### ISSUE THREAD

**Issue by vinaypuranik** [deislabs/akri#381]
Hi, 

Just wondering whether we already have some web UI tool for Akri besides what K8s web-ui-dashboard provides to get more insights... I am looking for something similar to Kafdrop (https://github.com/obsidiandynamics/kafdrop, _Kafdrop is a web UI for viewing Kafka topics and browsing consumer groups. The tool displays information such as brokers, topics, partitions, consumers, and lets you view messages_.)  exists for Akri which shows the information about the discovered devices and their statuses in a nice presentable way. 

Regards,
Vinay

**Comment by kate-goldenring** [comment]
Hi @vinaypuranik, we currently have Instance and brokers counts exposed as prometheus metrics that you can [sync into a grafana dashboard](https://docs.akri.sh/user-guide/monitoring-with-prometheus#akris-currently-exposed-metrics), but nothing as involved as Kafdrop. Would love to, though! Would presenting the content inside the device Instances be sufficient? What other data would you be interested in being displayed.

**Comment by vinaypuranik** [comment]
Thanks Kate for coming back on my query. We are also thinking what data would be ideal to show here. But, at first thought, we wanted to show the device and its status (which is currently the content inside the device instances) in a simple UI.  We are planning to build some external UI  to present the discovered devices and its status whether its online or offline, I was investigating if anybody has already built such tools.

**Comment by romoh** [comment]
@vinaypuranik This sounds like a great idea. Can you [create a feature request](https://github.com/deislabs/akri/issues/new?assignees=&labels=feature&template=feature_request.md&title=) to Akri that includes the details of what you would like to see in such UI?  Adding a sample UI in the issue would be appreciated.

**Comment by kate-goldenring** [comment]
> @vinaypuranik This sounds like a great idea. Can you [create a feature request](https://github.com/deislabs/akri/issues/new?assignees=&labels=feature&template=feature_request.md&title=) to Akri that includes the details of what you would like to see in such UI? Adding a sample UI in the issue would be appreciated.

This feature request would be a great start for proposing some UI and discussing/brainstorming any iterations of it.

**Comment by vinaypuranik** [comment]
> @vinaypuranik This sounds like a great idea. Can you [create a feature request](https://github.com/deislabs/akri/issues/new?assignees=&labels=feature&template=feature_request.md&title=) to Akri that includes the details of what you would like to see in such UI? Adding a sample UI in the issue would be appreciated.

Yeah, sure... will do. But, Is it fine if I create a feature request when the mockup is ready?

**Comment by vinaypuranik** [comment]
I have tried to create a sample UI on the data that I'd like to see.  Mostly it is the data we add in the `properties` map for a device.

![image](https://user-images.githubusercontent.com/6823168/134327205-06b7d3c1-5ecd-44a2-b66e-572bc14293d1.png)

It is just a raw version :) we can further iterate based on the results of further discussion/brainstorming 

If this is fine then, I'll go ahead and create a feature request

**Comment by vinaypuranik** [comment]
@romoh @kate-goldenring  Created a feature request here -> https://github.com/deislabs/akri/issues/384
