### ISSUE TITLE
modprobe: ERROR: could not insert 'v4l2loopback': Unknown symbol in module, or unknown parameter (see dmesg)

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#42]
**Describe the bug**

Challenged to run the End-to-End example cloud (!) VMs (GCP, DigitalOcean). Specifically `modprobe v4l2loopback`:

```bash
sudo modprobe v4l2loopback exclusive_caps=1 video_nr=1,2
modprobe: ERROR: could not insert 'v4l2loopback': Unknown symbol in module, or unknown parameter (see dmesg)
```
I suspect the issue is that dependenct modules aren't included on cloud VM kernels but I prefer to use cloud VMs because they're disposable and I can keep my primary workstation untainted by random installs.

**Output of `kubectl get pods,akrii,akric -o wide`**

N/A

**Kubernetes Version: [e.g. Native Kubernetes 1.19, MicroK8s 1.19, Minikube 1.19, K3s]**

N/A

**To Reproduce**
1. Create cloud VM (GCP, DigitalOcean)
2. Set up mock video devices ([link](https://github.com/deislabs/akri/blob/main/docs/end-to-end-demo.md#set-up-mock-udev-video-devices))
3. Attempt `modprobe v4l2loopback`

**Expected behavior**

No errors

dmesg:

```console
v4l2loopback: loading out-of-tree module taints kernel.
v4l2loopback: module verification failed: signature and/or required key missing - tainting kernel
v4l2loopback: Unknown symbol video_ioctl2 (err -2)
v4l2loopback: Unknown symbol v4l2_ctrl_handler_init_class (err -2)
v4l2loopback: Unknown symbol video_devdata (err -2)
v4l2loopback: Unknown symbol v4l2_ctrl_new_custom (err -2)
v4l2loopback: Unknown symbol video_unregister_device (err -2)
v4l2loopback: Unknown symbol video_device_alloc (err -2)
v4l2loopback: Unknown symbol v4l2_device_register (err -2)
v4l2loopback: Unknown symbol __video_register_device (err -2)
v4l2loopback: Unknown symbol v4l2_ctrl_handler_free (err -2)
v4l2loopback: Unknown symbol v4l2_device_unregister (err -2)
v4l2loopback: Unknown symbol video_device_release (err -2)
```
> **NOTE** the taint and module verification error are warnings only and may be ignored

**Additional context**

The solution I've found is:

```bash
sudo apt update && \
sudo apt -y install modules-extra-$(uname -r) && \
sudo apt -y install dkms
```

> **NOTE** the installs may possibly be combined

Then: 

```bash
curl http://deb.debian.org/debian/pool/main/v/v4l2loopback/v4l2loopback-dkms_0.12.5-1_all.deb ...
sudo dpkg -i v4l2loopback-dkms_0.12.5-1_all.deb
sudo modprobe v4l2loopback exclusive_caps=1 video_nr=1,2
```
Succeeds!

On GCP:

```bash
dkms status
v4l2loopback, 0.12.5, 5.4.0-1028-gcp, x86_64: installed
```

On DigitalOcean:

```bash
dkms status
v4l2loopback, 0.12.5, 5.4.0-51-generic, x86_64: installed
```

Hopefully this will help others that get stuck.

**Comment by kate-goldenring** [comment]
@DazWilkin, do you think we can close this since you added instructions for e2e on the cloud? Then, if we see more people hit this error, then we could add the additional install instructions:
```
sudo apt update && \
sudo apt -y install modules-extra-$(uname -r) && \
sudo apt -y install dkms
```

**Comment by DazWilkin** [comment]
Yes, please do!

I prefer to let repo owners decide whether to close|ignore comments.

I hope that's OK?

Thanks for asking.

**Comment by vladimirvivien** [comment]
Small correction: it should be `linux-modules-extra-$(uname -r)` in the solutions above, as in:

```
sudo apt update && \
sudo apt -y install linux-modules-extra-$(uname -r) && \
sudo apt -y install dkms
```
