### ISSUE TITLE
Simplify (!?) End-to-End

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#43]
**Is your feature request related to a problem? Please describe.**

My curiosity is piqued by akri; it sounds *very* interesting.

The End-to-End is *involved* and the video dependency is neat but it requires a bunch of dependencies that may (!?) cause problems (see #42).

**Is your feature request related to a way you would like Akri extended? Please describe.**

IIUC (!?) akri provides a mechanism by which IoT devices can be managed through Kubernetes apps.

The prototypical IoT examples are simple sensors shipping data to consumers and these can be readily emulated with random number generators pushing|pulling via some endpoint.

**Describe the solution you'd like**

I think it would be useful to have a simpler End-to-End example that consumes e.g. random numbers representing e.g. temperatures generated by simple off-cluster apps. Perhaps these apps could be simple sockets, TCP|UDP (less realistically, but practical, HTTP) emitters?

This would avoid the need to install dkms, v4l2loopback etc. to get a developer worker with a basic akri installation.

**Describe alternatives you've considered**

The Nessie [extensibility](https://github.com/deislabs/akri/blob/main/docs/extensibility.md) looks interesting and I'm going to try this. But, it would be helpful to have a baseline, known working installation (using something simple as described above) before proceeding with Nessie.

**Comment by kate-goldenring** [comment]
@DazWilkin Thank you for this awesome feedback. Would you be interested in putting in a PR for a simpler end-to-end demo like the one you mentioned?

**Comment by DazWilkin** [comment]
Thanks @kate-goldenring.

I got the E2E working on a cloud VM and plan to look (for) Nessie tomorrow to try to grok extensibility.

If I can make sense of it, I'll try to create another example.

I'm familiar with Kubernetes, less familiar with Rust (but keen to improve) and initiated in IoT, so akri is in a sweet spot of interest for me.

**Comment by kate-goldenring** [comment]
@DazWilkin, completely agree that Akri combines a lot of fun tech! When you say you want to "try to create another example". Are you saying you are interested in adding another discovery protocol, say Bluetooth, or interested in creating another extensibility example? I know that Nessie example is fairly cumbersome, so we'd love to hear any feedback you have. We also have some ideas we've made a proposal for making [protocol extension](https://github.com/deislabs/akri/blob/main/docs/proposals/simple-protocol-extension.md) less intensive.

**Comment by DazWilkin** [comment]
@kate-goldenring first step, I'd like to try to write another, simpler end-to-end example. This, along with Nessie, should help me better understand akri. I've only a passing familiarity with other IoT protocols (e.g. MQTT) and, given that I'm a rust noob too, I think I'd be challenged developing protocol support. Interesting though that would be.

I still don't fully grok akri and I'm deploying it and trying out examples in pursuit of understanding. I'm unsure what benefit akri provides an IoT developer **but** I know you guys are smart and see a possibility and so I'm pursuing this on trust. I suspect that the benefit is in creating Kubernetes-native resources that represent (abstractsions for) devices (MCUs, sensors etc.). I'll better my understanding through writing code.

**Comment by jiria** [comment]
@DazWilkin , as a side note, we presented Akri at https://edgeconference.io/. The registration is free and talks are available on demand now if you want to have a look for more context.

**Comment by DazWilkin** [comment]
@jiria @kate-goldenring I found the [video](https://youtu.be/ZbTLGuxH1UA) of your presentation on YouTube.

It is good and helped me better understand the project's motivations. The concept of manifesting devices as Kubernetes native resources, makes sense; I need to read the code and understand how this simplifies the code.

I still don't "get it" but I hope to gain a better understanding by writing more code.

Thanks for the pointer.

**Comment by jiria** [comment]
Thanks for sharing, did not realize it was on YouTube as well. Let us know if you had more questions.

**Comment by kate-goldenring** [comment]
Closing this thanks to a script @DazWilkin created (sref #56) to simplify the installation of all the e2e demo components for MicroK8s.
