### ISSUE TITLE
[End-to-End] MicroK8s: "Install Helm" redundant?

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#44]
**Describe the bug**

IIUC the End-to-End MicroK8s step to [Install Helm](https://github.com/deislabs/akri/blame/main/docs/end-to-end-demo.md#L61) is redundant. 

**Output of `kubectl get pods,akrii,akric -o wide`**

N/A

**Kubernetes Version: [e.g. Native Kubernetes 1.19, MicroK8s 1.19, Minikube 1.19, K3s]**

N/A

**To Reproduce**
1. Follow End-to-End instructions
2. Don't Install Helm
3. Do `microk8s.enable helm3`
4. For consistency: `alias helm=microk8s.helm3`
5. `helm version`

Yields: `version.BuildInfo{Version:"v3.0.2", ...`

**Expected behavior**

N/A

**Logs (please share snips of applicable logs)**

N/A

**Additional context**

Recommend: 

+ Drop the "Install Helm" step
+ Retain "Enable Helm for MicroK8s"
+ Consider adding `alias helm=microk8s.helm3`

**Comment by kate-goldenring** [comment]
Thanks, @DazWilkin! I didn't realize you can enable Helm for MicroK8s without installing helm first. This is a great addition! Would you be interested in putting in a PR for this fix?

**Comment by DazWilkin** [comment]
Thanks for the reply.

Sure! I'll do it tomorrow.
