### ISSUE TITLE
How to deploy akri to Google Compute Engine and DigitalOcean

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#50]
Wrote a [post](https://pretired.dazwilkin.com/posts/201022/) summarizing how to deploy the akri end-to-end to both Google Compute Engine and DigitalOcean.

Hope it helps foster adoption of akri!

**Comment by squillace** [comment]
hey! that's great -- any chance you could throw them into a PR? I love running things on DO.....

**Comment by DazWilkin** [comment]
Sure!

Where (in the repo) would you like the files added?

I propose one document for each cloud then folks can add equivalent instructions for other platforms?

**Comment by squillace** [comment]
I like it. @bfjelds @kate-goldenring what would you think?

**Comment by bfjelds** [comment]
@DazWilkin, this is incredible!  i like the idea of docs/end-to-end-demo-*.md (something like: gce | digital-ocean) files for each environment.

**Comment by DazWilkin** [comment]
Sounds good.

Will do it tomorrow.
