### ISSUE TITLE
DOCS: specify a minimum kubernetes version to work. 

### ISSUE THREAD

**Issue by squillace** [deislabs/akri#63]
**Is your feature request related to a problem? Please describe.**
No one likes it when their 1.14 cluster won't work. Make it clear what DOES work and beyond.

**Is your feature request related to a way you would like Akri extended? Please describe.**
DOCUMENT the minimum version.

**Describe the solution you'd like**
DOCUMENT the minimum version.

**Describe alternatives you've considered**

**Additional context**

**Comment by bfjelds** [comment]
Thank you for calling this out ... I agree that this is super important!

I think that the version-limiting features that Akri leverages are CRDs (I think GA in Kuberenetes v1.16) and Device-Plugin (I think in their current state in Kubernetes v1.10).

To try to verify minimum version, I tried using:

* 1.14 - helm install error'd with complaint about CRDs
* 1.15 - helm install error'd with complaint about CRDs
* 1.16 - helm installed correctly
