### ISSUE TITLE
Default capacity should not be 5

### ISSUE THREAD

**Issue by jiria** [deislabs/akri#65]
**Describe the bug**
Currently, the default broker spec capacity is 5. That seems to be an overkill.

**To Reproduce**
1. Follow the default e2e demo and the default helm chart deployment.
2. Capacity is set to 5.

**Expected behavior**
I think it would make more sense to start with 1 or 2. I would vote for 1 as HA can be an opt-in.

**Comment by bfjelds** [comment]
i agree completely
