### ISSUE TITLE
[Nessie] Get https://ghcr.io/v2/deislabs/akri/rust-crossbuild/manifests/x86_64-unknown-linux-gnu-0.1.16-0.0.6: unauthorized.

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#66]
**Describe the bug**

Walking through [Extensibility](https://github.com/deislabs/akri/blob/main/docs/extensibility.md), when trying to build `akri-agent` or `akri-controller` in [this](https://github.com/deislabs/akri/blob/main/docs/extensibility.md#installing-akri-with-your-new-configuration) step, receive unauthorized from deislabs' registry endpoint on GHCR.

I **assume** the build needs these intermediate images and that the repository is not public.

Recommend: make it public

```console
PREFIX=ghcr.io/dazwilkin BUILD_AMD64=1 BUILD_ARM32=0 BUILD_ARM64=0 make akri-controller
cargo install cross
    Updating crates.io index
     Ignored package `cross v0.2.1` is already installed, use --force to override
PKG_CONFIG_ALLOW_CROSS=1 cross build --release --target=x86_64-unknown-linux-gnu
Unable to find image 'ghcr.io/deislabs/akri/rust-crossbuild:x86_64-unknown-linux-gnu-0.1.16-0.0.6' locally
docker: Error response from daemon: Get https://ghcr.io/v2/deislabs/akri/rust-crossbuild/manifests/x86_64-unknown-linux-gnu-0.1.16-0.0.6: unauthorized.
See 'docker run --help'.
make: *** [build/akri-containers.mk:44: akri-cross-build-amd64] Error 125
```

**Kubernetes Version: [e.g. Native Kubernetes 1.19, MicroK8s 1.19, Minikube 1.19, K3s]**

N/A

**To Reproduce**

See summary.

**Expected behavior**

Permitted to pull from deislabs' GHCR registry|repos

**Logs (please share snips of applicable logs)**

**Additional context**

**Comment by bfjelds** [comment]
Thanks for highlighting this and sorry for the inconvenience!  We were trying to decide whether to make the intermediate builds public or to document how people can create their own ... in the end, we clearly didn't do either :(

To unblock you in the moment, you should be able to run `PREFIX=ghcr.io/dazwilkin BUILD_AMD64=1 BUILD_ARM32=0 BUILD_ARM64=0 make rust-crossbuild`

Then you can change `Cross.toml` to point at your intermediate container: `ghcr.io/deislabs/dazwilkin/rust-crossbuild:x86_64-unknown-linux-gnu-0.1.16-0.0.6`

**Comment by DazWilkin** [comment]
That works, thank you!
