### ISSUE TITLE
Add documentation on how to use udev outside of udevvideo

### ISSUE THREAD

**Issue by jiria** [deislabs/akri#68]
**Is your feature request related to a problem? Please describe.**
Currently, two use cases for Akri are spelled out in the docs. onvifvideo and udevvideo. But udev can be used for other devices as well.

**Describe the solution you'd like**
Please add a top level entry on how to use udev for non-video related leaf devices. Also consider making that a top level and reference the video use case from that as an example. Added bonus would be a template for Helm, but not necessary, if a sample Akri Configuration is provided and explained how it should be used.

**Comment by bfjelds** [comment]
good idea!  what would the default broker pod be for the udev template (the udevVideo template uses our udev video broker as a default)?

**Comment by jiria** [comment]
Do we need one? It can be specified as a parameter to helm chart or expected to be replaced from the template configuration, no?

Also re https://github.com/deislabs/akri/issues/69, there should be a way to not force one.

**Comment by bfjelds** [comment]
good call on https://github.com/deislabs/akri/issues/69.  definitely agree with that.

even still, if there is a brokerPodSpec there will likely need to be a default, what should that be?  maybe nginx?

**Comment by jiria** [comment]
Agreed on empty default.

Even for udevvideo/onvifvideo, not sure how much are our brokers really defaults as opposed to samples, but perhaps that is a separate question. We might not want to have them as defaults as folks might take dependency and then we would have to worry about breaking changes.

**Comment by kate-goldenring** [comment]
Other option would be to set nginx as default like we do in [DebugEcho](https://github.com/deislabs/akri/blob/0f9253dbd3875d3e8e5d5c3f1d1ee42e4e15e29a/deployment/helm/values.yaml#L86), but i like the option of no broker Pod. Then, people could use Akri to advertise udev resources and schedule their own pods to those resources.

**Comment by jiria** [comment]
Right; also, if we wanted to use a placeholder, would consider using pause instead of nginx for smaller footprint.

**Comment by kate-goldenring** [comment]
in the udev template, should we default have the instance and configuration services? It seems like no, since by default there is no broker

**Comment by jiria** [comment]
Makes sense; we should just document how to add them back.

**Comment by bfjelds** [comment]
i think i prefer the empty default to the nginx/pause version.  it seems like if we have a default of pause, then we'd need to introduce another parameter to toggle the broker/services on/off ... whereas if we defaulted the image to empty, we could use the image parameter (and whether it was set) as the toggle for the broker/services on/off.
