### ISSUE TITLE
How do I create a configuration without a broker?

### ISSUE THREAD

**Issue by jiria** [deislabs/akri#69]
How can I create a configuration that will detect leaf devices and advertise them as extended resources, but not deploy any brokers automatically?

**Comment by kate-goldenring** [comment]
Our documentation was not clear on how to do this and we were using Akri's sample brokers as defaults. #87 fixed this. Now, broker specs will not be added to the generic protocol Configurations unless a broker image is specified. This is explained in our [user guide](https://github.com/deislabs/akri/blob/main/docs/user-guide.md) and elaborated upon in our [documentation](https://github.com/deislabs/akri/blob/main/docs/requesting-akri-resources.md) on scheduling pods to resources advertised by Akri.
